{{- if .Values.horizonNetImport.enabled -}}
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ include "horizon-cli.fullname" . }}-netimport
  labels:
    {{- include "horizon-cli.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.horizonNetImport.schedule | quote }}
  suspend: {{ .Values.horizonNetImport.suspend }}
  successfulJobsHistoryLimit: {{ .Values.horizonNetImport.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.horizonNetImport.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.horizonNetImport.backoffLimit }}
      template:
        metadata:
          {{- with .Values.podLabels }}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "horizon-cli.serviceAccountName" . }}
          {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.image) "context" $) | nindent 10 }}
          containers:
            - name: horizon-cli-netimport
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ include "horizon-cli.fullname" . }}-credentials
              command:
                - /app/horizon-cli
                - netimport
                - kubernetes
                - --campaign={{ .Values.horizonNetImport.campaign }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
