apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon-cli.fullname" . }}-credentials
  labels:
    {{- include "horizon-cli.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENDPOINT: {{ .Values.horizonCliCredentials.endpoint | quote }}
  APIID: {{ .Values.horizonCliCredentials.apiID | quote }}
  APIKEY: {{ .Values.horizonCliCredentials.apiKey | quote }}
