{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "horizon-cli.serviceAccountName" . }}
  labels:
    {{- include "horizon-cli.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "horizon-cli.fullname" . }}-secret-reader
  labels:
    {{- include "horizon-cli.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "horizon-cli.fullname" . }}-read-secrets
  labels:
    {{- include "horizon-cli.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "horizon-cli.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "horizon-cli.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
